name: etc
description: ETC Mobile App.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  dio: ^3.0.9
  meta: ^1.1.8
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  geolocator: ^5.3.1
  carousel_slider: ^2.0.0
  getflutter: ^1.0.11
  intl: ^0.16.1
  share: ^0.6.4
  flutter_webview_plugin: ^0.3.11
  url_launcher: ^5.4.5
  table_calendar: ^2.2.3
  modal_progress_hud: ^0.1.3
  shimmer: ^1.1.1
  shared_preferences: ^0.5.7
  qr_flutter: ^3.2.0
  cached_network_image: ^2.2.0+1
  country_pickers: ^1.3.0
  image_picker: ^0.6.6+5
  google_maps_flutter: ^0.5.28+1
  fluster: ^1.1.2
  google_maps_cluster_manager: ^0.1.0
  launch_review: ^2.0.0
  mime: ^0.9.6+3




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    -  assets/
    -  assets/img/
    
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/Proxima-Nova-Regular.ttf
          weight: 400
        - asset: assets/fonts/Proxima-Nova-Light.ttf
          weight: 300
        - asset: assets/fonts/Proxima-Nova-Medium.ttf
          weight: 500
        - asset: assets/fonts/Proxima-Nova-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Proxima-Nova-Thin.ttf
          weight: 100
        
  #       - asset: fonts/Schyler-Italic.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
